apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pods
  namespace: facebook
  labels:
    app: httpd
    tier: frontend-backend
    version: v1
spec:
  containers:
  #Container 01
  - name: web
    image: httpd
    ports:
    - containerPort: 80
  #Container 02
  - name: redis
    image: redis