apiVersion: v1
kind: Pod
metadata:
  name: purple
spec:
  containers:
    - command:
        - sh
        - -c
        - echo The app is running! && sleep 3600
      image: busybox:1.28
      name: purple-container
  # Adding 2 init containers to execute sleep commands
  initContainers:
    - command:
        - sh
        - -c
        - sleep 60
      image: busybox:1.28
      name: warm-up-1
    - command: ["sh", "-c", "sleep 120"]
      image: busybox:1.28
      name: warm-up-2
# Both the init containers will get executed before the main container is started
# NAME     READY   STATUS     RESTARTS   AGE
# purple   0/1     Init:1/2   0          2m41s
# After 3mins(60+120seconds), output will be
# NAME     READY   STATUS    RESTARTS   AGE
# purple   1/1     Running   0          3m7s
